[package]
name = "levante-wp-api"
version = "0.1.0"
authors = ["Crazz <mhxdev@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
diesel = { version = "1.1.1", features = ["mysql"] }