[package]
name = "levante-wp-api"
version = "0.1.0"
authors = ["Crazz <mhxdev@gmail.com>"]

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"
diesel = { version = "1.0.0", features = ["mysql"] }
dotenv = "0.9.0"