
pub struct WpPost {
    pub date: String,
    pub date_gmt: String,
    pub guid: String,
    pub id: Option<i32>,
    pub link: String,
    pub modified: String,
    pub modified_gmt: String,
    pub slug: String,
    pub status: String,
    pub rtype: String,
    pub password: String,
    pub title: String,
    pub content: String,
    pub author: Option<i32>,
    pub excerpt: String,
    pub featured_media: Option<i32>,
    pub comment_status: String,
    pub ping_status: String,
    pub format: String,
    pub meta: [String],
    pub sticky: bool,
    pub template: String,
    pub categories: [i32],
    pub tags: [String],
}

pub struct WpPostRevisio {
    pub id: Option<i32>,
    pub date: String,
    pub date_gmt: String,
    pub guid: String,
    pub modified: String,
    pub modified_gmt: String,
    pub slug: String,
    pub parent: Option<i32>,
    pub title: String,
    pub content: String,
    pub author: Option<i32>,
    pub excerpt: String,
}

pub struct WpCategory {
    pub id: Option<i32>,
    pub count: String,
    pub description: String,
    pub link: String,
    pub name: String,
    pub taxonomy: String,
    pub slug: String,
    pub parent: Option<i32>,
    pub meta: [String],
}

pub struct WpTag {
    pub id: Option<i32>,
    pub count: String,
    pub description: String,
    pub link: String,
    pub name: String,
    pub taxonomy: String,
    pub slug: String,
    pub parent: Option<i32>,
    pub meta: [String],
}


pub struct WpPage {
    pub id: String,
    pub date: String,
    pub date_gmt: String,
    pub guid: String,
    pub modified: String,
    pub modified_gmt: String,
    pub slug: String,
    pub status: String,
    pub post_type: String,
    pub link: String,
    pub title: String,
    pub content: String,
    pub excerpt: String,
    pub author: Option<i32>,
    pub featured_media: Option<i32>,
    pub parent: Option<i32>,
    pub menu_order: String,
    pub comment_status: String,
    pub ping_status: String,
    pub template: String,
    pub meta: [String],
}

pub struct WpCommens {
    pub id: Option<i32>,
    pub author: Option<i32>,
    pub author_email: String,
    pub author_ip: String,
    pub author_name: String,
    pub author_url: String,
    pub author_user_agent: String,
    pub content: String,
    pub date: String,
    pub date_gmt: String,
    pub link: String,
    pub parent: Option<i32>,
    pub post: Option<i32>,
    pub status: String,
    pub rtype: String,
    pub author_avatar_urls: [String],
    pub meta: [String],
}

pub struct WpTaxonoms {
    pub capabilities: [String],
    pub description: String,
    pub hierarchical: bool,
    pub labels: [String],
    pub name: String,
    pub slug: String,
    pub show_cloud: bool,
    pub types: [String],
    pub rest_base: String,
}

pub struct WpMedia {
    pub date: String,
    pub date_gmt: String,
    pub guid: String,
    pub id: Option<i32>,
    pub link: String,
    pub modified: String,
    pub modified_gmt: String,
    pub slug: String,
    pub status: String,
    pub alt_type: String,
    pub title: String,
    pub author: Option<i32>,
    pub comment_status: String,
    pub ping_status: String,
    pub meta: [String],
    pub template: String,
    pub alt_text: String,
    pub caption: String,
    pub description: String,
    pub media_type: String,
    pub mime_type: String,
    pub media_details: [String],
    pub post: Option<i32>,
    pub source_url: String,
}

pub struct WpUses {
    pub id: Option<i32>,
    pub username: String,
    pub name: String,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub url: String,
    pub description: String,
    pub link: String,
    pub locale: String,
    pub nickname: String,
    pub slug: String,
    pub registered_date: String,
    pub roles: [String],
    pub password: String,
    pub capabilities: [String],
    pub extra: [String],
    pub avatar_urls: [String],
    pub meta: [String],
}

pub struct WpPostType {
    pub capabilities: [String],
    pub description: String,
    pub hierarchical: bool,
    pub labels: [String],
    pub name: String,
    pub slug: String,
    pub supports: [String],
    pub taxonomies: [String],
    pub rest_base: String,
}

pub struct WpPostStatus {
    pub name: String,
    pub private: bool,
    pub protected: bool,
    pub public: bool,
    pub queryable: bool,
    pub show_in_list: bool,
    pub slug: String,
}

pub struct WpSetting {
    pub title: String,
    pub description: String,
    pub timezone: String,
    pub date_format: String,
    pub time_format: String,
    pub start_of_week: Option<i32>,
    pub language: String,
    pub use_smilies: bool,
    pub default_category: Option<i32>,
    pub default_post_format: String,
    pub posts_per_page: Option<i32>,
    pub default_ping_status: String,
    pub default_comment_status: String,
}